### ISSUE TITLE
What's the status of the repo?

### ISSUE THREAD

**Issue by Pictor13** [libundo/Sublundo#7]
Hi @jdkato,

Great plugin idea, that allows hoarders like me to dribble the _terror of loosing trace_ and always be able to recover past data/work. 😉

I was wondering how stable is Sublundo at the moment.
I can't see any development since 2 years but there is still a [*scaring* warning note in the readme](https://user-images.githubusercontent.com/8785025/29885633-627d89ae-8d6c-11e7-9886-ccd389d18317.png):

> This package is in early development. Use with caution.

Is it still the case? Or is the plugin more or less stable/complete/1.0?

I'd love to give a try and use the plugin but I feel unsure if that could mess up something or loose any data that I work with (I didn't give a check at the code yet).

If it is stable then could make sense to change that misleading image 🙃

**Comment by jdkato** [comment]
The status is "unmaintained" for now (I just don't have time). I also think the warning is still accurate.

**Comment by Pictor13** [comment]
Thank you for answering; would be great if you could give an opinion on whether you consider it dangerous (potentially where) or stable enough to be used.

Does the plugin works just on the undo history or is there anything else that could break?
In the first case I'd still feel like giving a try, since the functionality would be pretty useful.

**Comment by jdkato** [comment]
The plugin, essentially, does two things: overload the built-in `undo` / `redo` commands and (optionally) stores a serialized copy of editing history for a file.

I don't consider it to be "dangerous," but I also don't want to be misleading about its development state.
