### ISSUE TITLE
[RESEARCH] Nodes visualization

### ISSUE THREAD

**Issue by sergeevabc** [libundo/Sublundo#8]
Dear Joseph,
Could you be so kind to enlighten what program was used to visualize that nodes tree?

![1]

[1]: https://user-images.githubusercontent.com/8785025/29885744-baac1096-8d6c-11e7-8105-f17b3bbe20d0.png

**Comment by jdkato** [comment]
I used D3.js -- there's a similar example here: http://bl.ocks.org/d3noob/8375092
